name: Release drafter auto labeler

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, edited]
#  pull_request_target:
#    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  calculate-policy-matrix:
    runs-on: ubuntu-latest
    outputs:
      policy_working_dirs: ${{ steps.policy-matrix.outputs.policy_working_dirs }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # checkout all history to do git diff
      - name: 'Policy Matrix'
        id: policy-matrix
        uses: ./.github/actions/calculate-policy-matrix
  auto_labeler:
    uses: ./.github/workflows/reusable-auto-labeler.yaml
    needs: calculate-policy-matrix
    permissions:
      contents: write
      pull-requests: write
    if: ${{ needs.calculate-policy-matrix.outputs.policy_working_dirs != '[]' }}
    strategy:
      fail-fast: true
      matrix:
        policy-working-dir: ${{ fromJSON(needs.calculate-policy-matrix.outputs.policy_working_dirs) }}
    with:
      policy-working-dir: ${{ matrix.policy-working-dir}}
