name: Release drafter auto labeler

on:
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize, edited]
  # pull_request_target event is required for autolabeler to support PRs from forks
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  calculate-policy-matrix:
    runs-on: ubuntu-latest
    outputs:
      policy_working_dirs: ${{ steps.policy-matrix.outputs.policy_working_dirs }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # checkout all history to do git diff
      - name: 'Policy Matrix'
        id: policy-matrix
        uses: ./.github/actions/policy-matrix
  auto_labeler:
    uses: ./.github/workflows/reusable-auto-labeler.yaml
    needs: calculate-policy-matrix
    permissions:
      contents: write
      pull-requests: write
    if: ${{ needs.calculate-policy-matrix.outputs.policy_working_dirs != '[]' }}
    strategy:
      fail-fast: true
      matrix:
        policy-working-dir: ${{ fromJSON(needs.calculate-policy-matrix.outputs.policy_working_dirs) }}
    with:
      policy-working-dir: ${{ matrix.policy-working-dir}}
