on:
  workflow_call:
    inputs:
      policy-working-dir:
        description: "Working directory of the policy. Useful for repos with policies in folders"
        required: false
        type: string
        default: "."

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "1.25"
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: "latest"
          install-only: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Policy linter
        shell: bash
        run: |
          make -C ${{ inputs.policy-working-dir}} lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "1.25"
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: "latest"
          install-only: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build policy
        shell: bash
        run: |
          make -C ${{ inputs.policy-working-dir}} policy.wasm
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "1.25"
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: "latest"
          install-only: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Policy unit tests
        shell: bash
        run: |
          make -C ${{ inputs.policy-working-dir}} test
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "1.25"
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: "latest"
          install-only: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Policy integration test
        shell: bash
        run: |
          make -C ${{ inputs.policy-working-dir}} e2e-tests
